package com.learningplatform.learningplatform.question;

public enum QuestionAttribute {

	SHAPE, ANIMAL, ANIMALFOOD, STORE, NUMERICALTHING, AREA, BUILD, BUILDMATERIAL, INCOME, EXPENSEFOOD,
	EXPENSECONSTRUCTION, INCOMEVISITORS, CITY, CUSTOMER
}
