package com.learningplatform.learningplatform.bkt;

public enum BktTypeConceptual {

	COMPUTATIONAL_RULES_SKILL, STEPS_NEEDED_SKILL, SOLVING_CARRY_TASKS_SKILL, AREA_CALCULATION_SKILL,
	CALCULATE_PROBABILITIES_SKILL, CHOOSE_CORRECT_FORMULAS_SKILL, CHOOSE_CORRECT_INFORMATION_SKILL,
	INSERT_CORRECT_VALUES_SKILL
}
